log_level: -4
http_server_addr: 127.0.0.1:8000
sql_db: postgres://user:pass@127.0.0.1:5432/ecom?sslmode=disable
broker:
  seed_brokers:
    - 127.0.0.1:19094
    - 127.0.0.1:29094
    - 127.0.0.1:39094
  schema_registry_urls:
    - http://127.0.0.1:8081
  topics:
    products_from_shop: products-from-shop
    products_to_storage: products-to-storage
    filter_product_stream: filter-product-stream
    filter_product_table: filter-product-group-table # <prefix>-table derived from consumers.filter_product_group
    client_events: client-events
  consumers:
    filter_product_group: filter-product-group
    product_blocker_group: product-blocker-group
    product_saver_group: product-saver-group
